version: "3.8"

services:
  wildbook:
    image: tomcat:9.0
    ports:
      - "8080:8080"
    volumes:
      - ./target/wildbook.war:/usr/local/tomcat/webapps/wildbook.war
      - .dockerfiles/docker-entrypoint.sh:/docker-entrypoint.sh
      - .dockerfiles/tomcat/server.xml:/usr/local/tomcat/conf/server.xml
      - .dockerfiles/tomcat/watermark.png:/usr/local/tomcat/watermark.png
      - .dockerfiles/tomcat/IA.json:/usr/local/tomcat/webapps/wildbook_data_dir/WEB-INF/classes/bundles/IA.json
      - .dockerfiles/tomcat/IA.properties:/usr/local/tomcat/webapps/wildbook_data_dir/WEB-INF/classes/bundles/IA.properties
      - .dockerfiles/tomcat/commonConfiguration.properties:/usr/local/tomcat/webapps/wildbook_data_dir/WEB-INF/classes/bundles/commonConfiguration.properties

  db:
    image: postgres:13.4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
    labels:
      - autoheal=true
    user: postgres
    volumes:
      - db-pgdata-var:/var/lib/postgresql/data
      - .dockerfiles/db/initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - intranet
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      WBIA_DB_NAME: "${WBIA_DB_NAME}"
      WBIA_DB_USER: "${WBIA_DB_USER}"
      WBIA_DB_PASSWORD: "${WBIA_DB_PASSWORD}"
      WILDBOOK_DB_NAME: "${WILDBOOK_DB_NAME}"
      WILDBOOK_DB_USER: "${WILDBOOK_DB_USER}"
      WILDBOOK_DB_PASSWORD: "${WILDBOOK_DB_PASSWORD}"

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 60
    labels:
      - autoheal=true
    volumes:
      - opensearch-var1:/usr/share/opensearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - intranet  # Connects the service to the intranet network
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - plugins.security.disabled=true
      - node.name=opensearch
      - cluster.initial_master_nodes=opensearch
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=${ES_THRESHOLD:-true}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "OPENSEARCH_INITIAL_ADMIN_PASSWORD=${OPENSEARCH_INITIAL_ADMIN_PASSWORD}"

networks:
  intranet:
    driver: bridge   # Defines the 'intranet' network with the 'bridge' driver

volumes:
  db-pgdata-var:
  opensearch-var1:
